env:
  node: true
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  import/no-extraneous-dependencies: ["error", {"devDependencies": false, "optionalDependencies": false, "peerDependencies": false}]
  import/prefer-default-export: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]

